Core: Fix view version ID deduplication with schema ID assignment (#14434)
Without this fix the test would fail with
```
Cannot set current version to unknown version: 3
java.lang.IllegalArgumentException: Cannot set current version to unknown version: 3
	at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkArgument(Preconditions.java:190)
	at org.apache.iceberg.view.ViewMetadata$Builder.setCurrentVersionId(ViewMetadata.java:241)
	at org.apache.iceberg.view.TestViewMetadata.deduplicatingViewVersionByIdAndAssigningSchemaId(TestViewMetadata.java:991)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```
because the the `ViewVersion` was assigned a new ID and later when we tried to re-assign the schema ID, we used the wrong `ViewVersion` instance (the one where the version ID was not re-assigned).